// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXkiexFDAiTtC9Zix0_fYo635fUUuRQ3g',
    appId: '1:854688285338:web:9f392f15f785f8dd00d523',
    messagingSenderId: '854688285338',
    projectId: 'communication-book-43007',
    authDomain: 'communication-book-43007.firebaseapp.com',
    storageBucket: 'communication-book-43007.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3AsKDG01Tyv_1JLNtEyJkGxGYa7x4O8',
    appId: '1:854688285338:android:2a5677f28ce5726000d523',
    messagingSenderId: '854688285338',
    projectId: 'communication-book-43007',
    storageBucket: 'communication-book-43007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICjxR69t88FAKe4QUNp8ogF2SwxS7Z64',
    appId: '1:854688285338:ios:4a9f69774e5b142500d523',
    messagingSenderId: '854688285338',
    projectId: 'communication-book-43007',
    storageBucket: 'communication-book-43007.appspot.com',
    iosBundleId: 'com.example.communicationBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAICjxR69t88FAKe4QUNp8ogF2SwxS7Z64',
    appId: '1:854688285338:ios:d90cf1c196814d0900d523',
    messagingSenderId: '854688285338',
    projectId: 'communication-book-43007',
    storageBucket: 'communication-book-43007.appspot.com',
    iosBundleId: 'com.example.communicationBook.RunnerTests',
  );
}
